#!/bin/sh

pacman_conf_file=/etc/pacman.conf

cache_dir=`awk '/^CacheDir/ {print $3}' $pacman_conf_file`

if [ ! -d "$cache_dir" ]
then
    cache_dir=/var/cache/pacman/pkg/
fi

if [ "${cache_dir: -1}" != '/' ]
then
    cache_dir=$cache_dir'/'
fi

files=`find $cache_dir -name '*.pkg.tar.xz' -type f`

packages=`pacman -Qv | awk '{print $1"-"$2}'`

rm_files=()
rm_filenames=()

get_pkg_files()
{
    i=0
    for file in $files
    do
        file_name=`basename ${file%\-*.pkg.tar.xz}`
        if [ `echo $packages | grep $file_name -c` -eq '0' ]
        then
            rm_files[$i]=$file
            rm_filenames[$i]=`basename $file`
            i=$(($i+1))
        fi
    done
}

get_pkg_files

if [ "" == "$rm_files" ]
then
    echo 'No package needs to remove'
    exit
fi

echo ${rm_filenames[*]}
echo 'Confirm to remove the expired packages, type y|Y[es]: (default: no) '

read flag

rm_pkg_files()
{
    for file in ${rm_files[*]}
    do
        echo 'removing '$file
        rm $file
    done
}

case $flag in
    'y'|'Y'|'yes'|'Yes')
        rm_pkg_files
        echo 'fin'
        ;;
    *)
        echo 'Nothing done, quit'
        ;;
esac
